package com.ccunix.icar.basedb.dao;
import java.util.List;
import com.ccunix.icar.basedb.domain.T_u_order_implementation;
public interface T_u_order_implementation_Dao_Iface {
public void insert_t_u_order_implementation(T_u_order_implementation t_u_order_implementation) throws Exception;
public void update_t_u_order_implementation(T_u_order_implementation t_u_order_implementation) throws Exception;
public void delete_t_u_order_implementation(T_u_order_implementation t_u_order_implementation) throws Exception;
public List queryAll_t_u_order_implementation(T_u_order_implementation t_u_order_implementation) throws Exception;
public List queryBy_t_u_order_implementation(T_u_order_implementation t_u_order_implementation) throws Exception;
}
