package com.ccunix.icar.basedb.service;
import com.ccunix.icar.basedb.domain.T_u_statistic_day_of_franchise;
import java.util.List;
public interface T_u_statistic_day_of_franchise_Service_Iface {
public void insert_t_u_statistic_day_of_franchise(T_u_statistic_day_of_franchise t_u_statistic_day_of_franchise) throws Exception;
public void update_t_u_statistic_day_of_franchise(T_u_statistic_day_of_franchise t_u_statistic_day_of_franchise) throws Exception;
public void delete_t_u_statistic_day_of_franchise(T_u_statistic_day_of_franchise t_u_statistic_day_of_franchise) throws Exception;
public List queryAll_t_u_statistic_day_of_franchise(T_u_statistic_day_of_franchise t_u_statistic_day_of_franchise) throws Exception;
public List queryBy_t_u_statistic_day_of_franchise(T_u_statistic_day_of_franchise t_u_statistic_day_of_franchise) throws Exception;
}
