package com.ccunix.icar.basedb.service;
import com.ccunix.icar.basedb.domain.T_u_integral_usergoods;
import java.util.List;
public interface T_u_integral_usergoods_Service_Iface {
public void insert_t_u_integral_usergoods(T_u_integral_usergoods t_u_integral_usergoods) throws Exception;
public void update_t_u_integral_usergoods(T_u_integral_usergoods t_u_integral_usergoods) throws Exception;
public void delete_t_u_integral_usergoods(T_u_integral_usergoods t_u_integral_usergoods) throws Exception;
public List queryAll_t_u_integral_usergoods(T_u_integral_usergoods t_u_integral_usergoods) throws Exception;
public List queryBy_t_u_integral_usergoods(T_u_integral_usergoods t_u_integral_usergoods) throws Exception;
}
