package com.ccunix.icar.basedb.service;
import com.ccunix.icar.basedb.domain.T_u_accout_franchisee_system;
import java.util.List;
public interface T_u_accout_franchisee_system_Service_Iface {
public void insert_t_u_accout_franchisee_system(T_u_accout_franchisee_system t_u_accout_franchisee_system) throws Exception;
public void update_t_u_accout_franchisee_system(T_u_accout_franchisee_system t_u_accout_franchisee_system) throws Exception;
public void delete_t_u_accout_franchisee_system(T_u_accout_franchisee_system t_u_accout_franchisee_system) throws Exception;
public List queryAll_t_u_accout_franchisee_system(T_u_accout_franchisee_system t_u_accout_franchisee_system) throws Exception;
public List queryBy_t_u_accout_franchisee_system(T_u_accout_franchisee_system t_u_accout_franchisee_system) throws Exception;
}
