package com.ccunix.icar.basedb.service;
import com.ccunix.icar.basedb.domain.T_u_receive_money_from_alipay;
import java.util.List;
public interface T_u_receive_money_from_alipay_Service_Iface {
public void insert_t_u_receive_money_from_alipay(T_u_receive_money_from_alipay t_u_receive_money_from_alipay) throws Exception;
public void update_t_u_receive_money_from_alipay(T_u_receive_money_from_alipay t_u_receive_money_from_alipay) throws Exception;
public void delete_t_u_receive_money_from_alipay(T_u_receive_money_from_alipay t_u_receive_money_from_alipay) throws Exception;
public List queryAll_t_u_receive_money_from_alipay(T_u_receive_money_from_alipay t_u_receive_money_from_alipay) throws Exception;
public List queryBy_t_u_receive_money_from_alipay(T_u_receive_money_from_alipay t_u_receive_money_from_alipay) throws Exception;
}
