package com.ccunix.icar.basedb.service;
import com.ccunix.icar.basedb.domain.T_u_send_mobile_message;
import java.util.List;
public interface T_u_send_mobile_message_Service_Iface {
public void insert_t_u_send_mobile_message(T_u_send_mobile_message t_u_send_mobile_message) throws Exception;
public void update_t_u_send_mobile_message(T_u_send_mobile_message t_u_send_mobile_message) throws Exception;
public void delete_t_u_send_mobile_message(T_u_send_mobile_message t_u_send_mobile_message) throws Exception;
public List queryAll_t_u_send_mobile_message(T_u_send_mobile_message t_u_send_mobile_message) throws Exception;
public List queryBy_t_u_send_mobile_message(T_u_send_mobile_message t_u_send_mobile_message) throws Exception;
}
